import { useEffect, useMemo, useState } from 'react';
import { getClasses } from '../api/class';
import { getSubjects } from '../api/subject';
import { getAcademicYearMasterData } from '../api/academicYearConfig';
import { calculateSemesterResults, calculateSubjectAverages, changeGradeBookStatus, getGradeBook, getGradeBookStudents, updateScores } from '../api/gradeBook';

export default function GradesManagementPage({ selectedYearId, selectedSemesterId }: { selectedYearId: string; selectedSemesterId: string }) {
  const [classes,setClasses]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]);const [classId,setClassId]=useState(''),[subjectId,setSubjectId]=useState('');
  const [book,setBook]=useState<any>(null),[scores,setScores]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{setBook(null);setScores([]);setClassId('');setSubjectId('');if(!selectedYearId)return;Promise.all([getClasses({academicYearId:selectedYearId,size:200}),getSubjects(),getAcademicYearMasterData(selectedYearId)]).then(([classData,allSubjects,config]:any[])=>{setClasses(classData.content||classData||[]);setSubjects((allSubjects||[]).filter((s:any)=>config.subjectIds.includes(s.id)));}).catch(e=>setError(e.message));},[selectedYearId]);
  async function load(){if(!classId||!subjectId||!selectedSemesterId)return;try{const b:any=await getGradeBook(Number(classId),Number(subjectId),Number(selectedSemesterId));setBook(b);setScores(await getGradeBookStudents(b.id) as any[]);}catch(e:any){setError(e.message);}}
  const students=useMemo(()=>{const map=new Map<number,any>();for(const row of scores){const student=map.get(row.studentId)||{id:row.studentId,name:row.studentName,code:row.studentCode,values:{},average:row.average};student.values[row.gradeItemId]=row.score;student.average=row.average;map.set(row.studentId,student);}return [...map.values()];},[scores]);
  async function saveItem(itemId:number){const entries=students.map(s=>({studentId:s.id,score:s.values[itemId]??null,isGraded:s.values[itemId]!==null&&s.values[itemId]!==undefined}));try{await updateScores(itemId,entries,'Admin cập nhật bảng điểm');setMessage('Đã lưu điểm.');await load();}catch(e:any){setError(e.message);}}
  if(!selectedYearId||!selectedSemesterId)return <div className="notice warning">Chọn năm học và học kỳ để quản lý điểm.</div>;
  return <div><div className="page-header"><div><h1>Quản lý điểm</h1><p>Điểm được cô lập theo năm học, học kỳ, lớp và môn.</p></div></div>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice success">{message}</div>}
    <section className="form-grid"><label className="form-group">Lớp<select value={classId} onChange={e=>{setClassId(e.target.value);setBook(null);}}><option value="">Chọn lớp</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="form-group">Môn<select value={subjectId} onChange={e=>{setSubjectId(e.target.value);setBook(null);}}><option value="">Chọn môn</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button onClick={load}>Mở bảng điểm</button></section>
    {book&&<><div style={{display:'flex',gap:8,justifyContent:'flex-end',margin:'16px 0',flexWrap:'wrap'}}><span className="badge-status active">{book.status}</span><button className="secondary-button" onClick={async()=>{try{await calculateSubjectAverages(book.id);setMessage('Đã tính điểm trung bình môn.');await load();}catch(e:any){setError(e.message);}}}>Tính ĐTB môn</button><button className="secondary-button" onClick={async()=>{try{await calculateSemesterResults(Number(classId),Number(selectedSemesterId));setMessage('Đã tính kết quả trung bình học kỳ.');}catch(e:any){setError(e.message);}}}>Tính kết quả học kỳ</button><button onClick={async()=>{await changeGradeBookStatus(book.id,'PUBLISHED');await load();}}>Công bố</button><button onClick={async()=>{await changeGradeBookStatus(book.id,'LOCKED');await load();}}>Khóa điểm</button></div><div className="table-wrap"><table><thead><tr><th>Học sinh</th>{book.items.map((i:any)=><th key={i.id}>{i.name}<small style={{display:'block'}}>HS {i.weight} · {i.entryRole==='ADMIN'?'Nhà trường':'Giáo viên'}</small></th>)}<th>ĐTB</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small style={{display:'block'}}>{s.code}</small></td>{book.items.map((i:any)=><td key={i.id}><input type="number" min="0" max="10" step="0.1" disabled={i.entryRole==='SUBJECT_TEACHER'||book.status==='LOCKED'} value={s.values[i.id]??''} onChange={e=>setScores(rows=>rows.map(r=>r.studentId===s.id&&r.gradeItemId===i.id?{...r,score:e.target.value===''?null:Number(e.target.value)}:r))} />{i.entryRole!=='SUBJECT_TEACHER'&&book.status!=='LOCKED'&&<button className="secondary-button" onClick={()=>saveItem(i.id)}>Lưu cột</button>}</td>)}<td><strong>{s.average??'—'}</strong></td></tr>)}</tbody></table></div></>}
  </div>;
}
