import { useEffect, useState } from 'react';
import { applyGradeTemplateToYear, createGradeTemplate, getGradeTemplates, getYearGradeConfig, type GradeConfig, type GradeConfigItem } from '../api/gradeConfiguration';

const defaults: GradeConfigItem[] = [
  { code: 'TX', displayName: 'Thường xuyên', weight: 1, quantity: 2, entryRole: 'SUBJECT_TEACHER', assessmentType: 'SCORE', requiredEntry: true, displayOrder: 0 },
  { code: 'GK', displayName: 'Giữa kỳ', weight: 2, quantity: 1, entryRole: 'ADMIN', assessmentType: 'SCORE', requiredEntry: true, displayOrder: 1 },
  { code: 'CK', displayName: 'Cuối kỳ', weight: 3, quantity: 1, entryRole: 'ADMIN', assessmentType: 'SCORE', requiredEntry: true, displayOrder: 2 },
];

export default function GradeConfigurationPage({ selectedYearId, selectedYearStatus }: { selectedYearId: string; selectedYearStatus?: string }) {
  const [templates, setTemplates] = useState<GradeConfig[]>([]); const [name,setName]=useState('Cấu hình chuẩn');
  const [items,setItems]=useState<GradeConfigItem[]>(defaults); const [error,setError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
  const [yearConfig,setYearConfig]=useState<GradeConfig|null>(null);
  const load=()=>getGradeTemplates().then(setTemplates).catch((e:any)=>setError(e.message)); useEffect(()=>{ void load(); },[]);
  useEffect(()=>{setYearConfig(null);if(selectedYearId)void getYearGradeConfig(selectedYearId).then(setYearConfig).catch(()=>setYearConfig(null));},[selectedYearId]);
  const update=(index:number,patch:Partial<GradeConfigItem>)=>setItems(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));
  async function save(){if(!name.trim()||items.length===0)return setError('Nhập tên mẫu và ít nhất một đầu điểm.');setSaving(true);setError('');try{await createGradeTemplate(name.trim(),items.map((item,index)=>({...item,displayOrder:index,code:item.code.trim().toUpperCase()})));setMessage('Đã lưu mẫu cấu hình đầu điểm.');await load();}catch(e:any){setError(e.message);}finally{setSaving(false);}}
  async function apply(templateId:number){if(!selectedYearId)return setError('Hãy chọn năm học ở header.');setSaving(true);setError('');try{const config=await applyGradeTemplateToYear(selectedYearId,templateId);setYearConfig(config);setMessage('Đã áp dụng mẫu cho năm học đang chọn. Hãy kiểm tra dữ liệu lại.');}catch(e:any){setError(e.message);}finally{setSaving(false);}}
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">Bước 2</span><h1>Cấu hình đầu điểm</h1><p>Tạo mẫu dùng lại cho nhiều năm học. Mỗi năm giữ một bản snapshot riêng.</p></div></section>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice success">{message}</div>}
    {selectedYearId&&<div className={`notice ${yearConfig?'success':'warning'}`}>{yearConfig?`Năm học đang chọn đã áp dụng mẫu “${yearConfig.name}”.`:'Năm học đang chọn chưa có cấu hình đầu điểm. Chọn một mẫu bên dưới để áp dụng.'}</div>}
    <div className="master-data-layout"><section className="step-card" style={{display:'block'}}><h3>Mẫu đã lưu</h3>{templates.map(template=><article key={template.id} style={{border:'1px solid var(--line)',borderRadius:12,padding:14,marginBottom:10}}><strong>{template.name}</strong><small style={{display:'block',color:'var(--muted)'}}>Phiên bản {template.version} · {template.items.length} loại đầu điểm</small><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:8}}>{template.items.map(item=><span className="badge-status active" key={item.id}>{item.displayName} · HS {item.weight} · SL {item.quantity}</span>)}</div>{!yearConfig&&<button style={{marginTop:10}} disabled={!selectedYearId||selectedYearStatus==='COMPLETED'||saving} onClick={()=>apply(template.id)}>Áp dụng cho năm học đang chọn</button>}</article>)}{templates.length===0&&<div className="notice warning">Chưa có mẫu. Hãy tạo mẫu đầu tiên trước khi tạo năm học.</div>}</section>
      <aside className="master-data-side"><div className="master-data-form-card"><h3>Tạo mẫu đầu điểm</h3><label className="form-group">Tên mẫu<input value={name} onChange={e=>setName(e.target.value)} /></label><div style={{display:'grid',gap:10}}>{items.map((item,index)=><div key={`${item.code}-${index}`} style={{border:'1px solid var(--line)',borderRadius:10,padding:10}}><div style={{display:'grid',gridTemplateColumns:'1fr 2fr',gap:8}}><label className="form-group">Mã<input value={item.code} onChange={e=>update(index,{code:e.target.value})}/></label><label className="form-group">Tên đầu điểm<input value={item.displayName} onChange={e=>update(index,{displayName:e.target.value})}/></label></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><label className="form-group">Hệ số<input type="number" min={1} value={item.weight} onChange={e=>update(index,{weight:Number(e.target.value)})}/></label><label className="form-group">Số lượng<input type="number" min={1} value={item.quantity} onChange={e=>update(index,{quantity:Number(e.target.value)})}/></label></div><label className="form-group">Người nhập<select value={item.entryRole} onChange={e=>update(index,{entryRole:e.target.value as GradeConfigItem['entryRole']})}><option value="SUBJECT_TEACHER">Giáo viên bộ môn</option><option value="ADMIN">Admin/nhà trường</option><option value="SUBJECT_TEACHER_AND_ADMIN">Giáo viên và admin</option></select></label><button className="danger" onClick={()=>setItems(rows=>rows.filter((_,i)=>i!==index))}>Xóa</button></div>)}</div><button className="secondary-button" onClick={()=>setItems(rows=>[...rows,{code:`D${rows.length+1}`,displayName:'Đầu điểm mới',weight:1,quantity:1,entryRole:'SUBJECT_TEACHER',assessmentType:'SCORE',requiredEntry:true,displayOrder:rows.length}])}>+ Thêm đầu điểm</button><button onClick={save} disabled={saving}>{saving?'Đang lưu…':'Lưu mẫu cấu hình'}</button></div></aside>
    </div></div>;
}
